env:
  node: true
extends: 'eslint:recommended'
rules:
  es6:
    - error
    - true
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
